version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
  - dependency-name: NJsonSchema
    versions:
    - 10.3.3
    - 10.3.4
    - 10.3.5
    - 10.3.6
    - 10.3.7
    - 10.3.8
    - 10.3.9
  - dependency-name: XunitXml.TestLogger
    versions:
    - 2.1.45
    - 3.0.56
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.8.0
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - 2.16.0
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/System.Management.Automation"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
- package-ecosystem: nuget
  directory: "/test/tools/Modules"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.Win32.Registry.AccessControl
    versions:
    - ">= 0"
  - dependency-name: Microsoft.Windows.Compatibility
    versions:
    - ">= 0"
  - dependency-name: System.*
    versions:
    - ">= 0"
- package-ecosystem: nuget
  directory: "/src/Modules"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
